# Generated by Django 2.0 on 2018-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
