# Generated by Django 2.0 on 2018-02-15 09:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methode', models.CharField(choices=[('CASH', 'Cash'), ('CRIDIT', 'VISA/MASTER'), ('CHEQUE', 'Cheque')], max_length=11)),
                ('instalment_details', models.CharField(blank=True, max_length=128)),
                ('instalment_date', models.DateField(blank=True, default=datetime.date(2018, 2, 15))),
                ('instalment_value', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memebership_code', models.CharField(max_length=6, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('membership_start', models.DateField(default=datetime.datetime.today)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('days_left_to_renewal', models.IntegerField(editable=False)),
                ('memebership_type', models.CharField(choices=[('F', 'Complementary'), ('N', 'Annual'), ('L', 'Life Time')], default='N', max_length=1)),
                ('fees', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('Mr', 'Male'), ('Mrs', 'Female')], default='Mr', max_length=4)),
                ('birthDay', models.DateField(default='1980-01-01')),
                ('age', models.IntegerField(editable=False)),
                ('job_title', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(max_length=128)),
                ('email2', models.EmailField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('phone2', models.CharField(blank=True, max_length=16, null=True)),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('al_ahly', models.BooleanField(default=False)),
                ('Al_Zamalek', models.BooleanField(default=False)),
                ('Wadi_Degla', models.BooleanField(default=False)),
                ('New_Giza', models.BooleanField(default=False)),
                ('Al_Jazira', models.BooleanField(default=False)),
                ('Al_Said', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('no_of_submembers', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('User_Name', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.CharField(blank=True, max_length=128)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('required_fees', models.PositiveIntegerField(default=0)),
                ('payments_total', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('current_credit', models.IntegerField(default=0, editable=False)),
                ('number_of_Instalment', models.PositiveIntegerField(default=1, editable=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SingleParentSubmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Mr', 'Male'), ('Mrs', 'Female')], default='Mr', max_length=4)),
                ('birthDay', models.DateField(default='2000-01-01')),
                ('age', models.PositiveIntegerField(editable=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('sub_member_active', models.BooleanField(default=True)),
                ('job_title', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('main_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='SpouseSubmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Mr', 'Male'), ('Mrs', 'Female')], default='Mr', max_length=4)),
                ('birthDay', models.DateField(default='2000-01-01')),
                ('age', models.PositiveIntegerField(editable=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('sub_member_active', models.BooleanField(default=True)),
                ('job_title', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('main_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Spouse',
            },
        ),
        migrations.CreateModel(
            name='Under21SubMeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Mr', 'Male'), ('Mrs', 'Female')], default='Mr', max_length=4)),
                ('birthDay', models.DateField(default='2000-01-01')),
                ('age', models.PositiveIntegerField(editable=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('sub_member_active', models.BooleanField(default=True)),
                ('School', models.CharField(blank=True, max_length=32, null=True)),
                ('Grade', models.CharField(blank=True, max_length=32, null=True)),
                ('Sport', models.CharField(blank=True, max_length=64, null=True)),
                ('main_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Under 21',
            },
        ),
        migrations.AddField(
            model_name='instalment',
            name='payment_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Payment'),
        ),
    ]
