# Generated by Django 2.0 on 2018-01-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthDay',
            field=models.DateField(default='1980-01-01'),
        ),
        migrations.AlterField(
            model_name='submember',
            name='birthDay',
            field=models.DateField(default='2008-01-01'),
        ),
    ]
