# Generated by Django 2.0 on 2018-02-20 16:46

import datetime
from django.db import migrations, models
import members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_singleinlawsubmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleinlawsubmember',
            options={'verbose_name': 'In-Law', 'verbose_name_plural': 'In-Law'},
        ),
        migrations.AlterModelOptions(
            name='singleparentsubmember',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parent'},
        ),
        migrations.AlterModelOptions(
            name='spousesubmember',
            options={'verbose_name': 'Spouse', 'verbose_name_plural': 'Spouse'},
        ),
        migrations.AlterModelOptions(
            name='under21submeber',
            options={'verbose_name': 'Child Under 21', 'verbose_name_plural': 'Children Under 21'},
        ),
        migrations.AlterField(
            model_name='instalment',
            name='instalment_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 2, 20)),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[members.validators.clean_phone]),
        ),
    ]
