# Generated by Django 2.0 on 2018-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180127_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submember',
            name='sub_membership_type',
            field=models.CharField(choices=[('C', 'Child-Under 12'), ('SD', 'Sun/Daughter 12+'), ('S', 'Spouse')], default='S', max_length=2),
        ),
    ]
