# Generated by Django 2.0 on 2018-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180203_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='other_memberships',
            field=models.CharField(blank=True, choices=[('ALAHLY', 'Al-Ahly'), ('ALZAMALEK', 'Al-Zamalek'), ('WADIDIGLA', 'Wadi-Digla'), ('ALJAZIRA', 'Al-Jazira'), ('NEWGIZA', 'New-Giza'), ('ALSAID', 'Al-Said')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='memebership_type',
            field=models.CharField(choices=[('F', 'Complementary'), ('N', 'Annual'), ('L', 'Life Time')], default='N', max_length=1),
        ),
    ]
