# Generated by Django 2.0 on 2018-02-20 16:53

from django.db import migrations, models
import members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180220_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[members.validators.clean_phone]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone2',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[members.validators.clean_phone]),
        ),
        migrations.AlterField(
            model_name='singleinlawsubmember',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[members.validators.clean_phone]),
        ),
        migrations.AlterField(
            model_name='singleparentsubmember',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[members.validators.clean_phone]),
        ),
        migrations.AlterField(
            model_name='spousesubmember',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[members.validators.clean_phone]),
        ),
    ]
