# Generated by Django 2.0 on 2018-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180128_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
