# Generated by Django 2.0 on 2018-02-23 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180220_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalment',
            name='instalment_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 2, 23)),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='payment_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='members.Payment'),
        ),
    ]
