# Generated by Django 2.0 on 2018-01-29 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180129_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Name',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
