# Generated by Django 2.0 on 2018-02-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180205_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='other_memberships',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
