# Generated by Django 2.0 on 2018-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180205_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='other_memberships',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
