# Generated by Django 2.0 on 2018-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180129_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
