# Generated by Django 2.0 on 2018-03-02 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180223_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email2',
        ),
        migrations.AddField(
            model_name='member',
            name='addetional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagarm',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='abcd1234', max_length=512),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='instalment_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 3, 2)),
        ),
    ]
