# Generated by Django 2.0 on 2018-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180129_1602'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='member',
        #     name='fees',
        #     field=models.PositiveIntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name='submember',
            name='birthDay',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='submember',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='submember',
            name='sub_membership_type',
            field=models.CharField(choices=[('C', 'Child-Under 21'), ('SD', 'Father/Mother'), ('S', 'Spouse')], default='S', max_length=2),
        ),
    ]
