# Generated by Django 2.0 on 2018-02-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180205_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='other_memberships',
        ),
        migrations.AddField(
            model_name='member',
            name='Al_Jazira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Al_Said',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Al_Zamalek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='New_Giza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Wadi_Degla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='al_ahly',
            field=models.BooleanField(default=False),
        ),
    ]
