# Generated by Django 2.0 on 2018-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180130_0925'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='member',
        #     name='fees',
        #     field=models.PositiveIntegerField(default=0),
        # ),
        migrations.AlterField(
            model_name='member',
            name='memebership_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
