# Generated by Django 2.0 on 2018-01-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180130_1028'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='member',
    #         name='fees',
    #         field=models.PositiveIntegerField(default=0),
    #     ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
