# Generated by Django 2.0 on 2018-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180205_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
