# Generated by Django 2.0 on 2018-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20180207_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_total',
            new_name='payments_total',
        ),
        migrations.AddField(
            model_name='payment',
            name='number_of_Instalment',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
