# Generated by Django 2.0 on 2018-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180207_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalment',
            name='instalment_value',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payments_total',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
