# Generated by Django 2.0 on 2018-02-07 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20180207_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalment',
            name='instalment_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 2, 7)),
        ),
    ]
