# Generated by Django 2.0 on 2018-02-07 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20180207_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalment',
            name='instalment_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 2, 7)),
        ),
    ]
