# Generated by Django 2.0 on 2018-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20180207_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_methode',
        ),
        migrations.AddField(
            model_name='payment',
            name='current_credit',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='required_fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payments_total',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
