# Generated by Django 2.0 on 2018-02-08 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20180207_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalment',
            name='instalment_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 2, 8)),
        ),
        migrations.AlterField(
            model_name='member',
            name='User_Name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
