# Generated by Django 2.0 on 2018-02-08 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20180208_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='User_Name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
